#= require jquery
#= require jquery_ujs
#= require twitter/bootstrap
#= require_directory ./admin
#= require_directory ./shared
#= require jquery_nested_form
#= require admin/metisMenu.min
# require tinymce-jquery
#= require angular
